### ISSUE TITLE
[Doc] Inquiry on MSCCL++ Algorithms

### ISSUE THREAD

**Issue by jhlee508** [microsoft/mscclpp#269]
Hi, mscclpp's developers. I am just curious about the algorithms that mscclpp uses. 

Direct information on MSCCL++ is hard to find in public resources, especially regarding whether it is an extension or modification of NCCL, and whether it uses algorithms other than Ring or Tree. 

If you could provide any details on whether it utilizes standard algorithms like Ring or Tree, or if it employs different algorithms, that would be helpful.

Thank you.

**Comment by chhwang** [comment]
@jhlee508 MSCCL++ is a completely separate project from NCCL. A small part of our code is borrowed from NCCL and NVIDIA-licensed, though (in v0.4.2, [debug.cc](https://github.com/microsoft/mscclpp/blob/v0.4.2/src/debug.cc), [socket.cc](https://github.com/microsoft/mscclpp/blob/v0.4.2/src/bootstrap/socket.cc), [debug.h](https://github.com/microsoft/mscclpp/blob/v0.4.2/src/include/debug.h), and [utils_internal.hpp](https://github.com/microsoft/mscclpp/blob/v0.4.2/src/include/utils_internal.hpp)).

MSCCL++ itself does not implement any collective communication algorithm. MSCCL++ users are supposed to do that. We have a few example algorithms in our test code.
