### ISSUE TITLE
[Bug]Meet IB problem in single node experiment?

### ISSUE THREAD

**Issue by TonyWu199** [microsoft/mscclpp#274]
Hi developers,
     It is a really nice work and I try to reproduct in one node with 8 gpus. However, I meet the IB problems below in both UT and collective communication case. 
### The UT
command:
```mpirun -np 2 ./test/mp_unit_tests```
![image](https://github.com/microsoft/mscclpp/assets/22834799/6c2e4654-b566-4ce2-a251-f778487997cb)
### The all_reduce_test in c++
command:
```mpirun --bind-to numa -np 8 ./test/mscclpp-test/allreduce_test_perf -b 3m -e 48m -G 100 -n 100 -w 20 -f 2 -k 5```
![image](https://github.com/microsoft/mscclpp/assets/22834799/fafa4759-cc4b-4315-8f13-a2df4d4dd808)
In my view, the gpu communication intra a single node is unrelated to IB, right? 
Could you help fix this problem or maybe some walkarounds?

**Comment by Binyang2014** [comment]
Please refer this comment: https://github.com/microsoft/mscclpp/issues/254#issuecomment-1926355914
