### ISSUE TITLE
Using MSCCL++ smchannel/proxy_channel within Triton Kernels

### ISSUE THREAD

**Issue by rajagond** [microsoft/mscclpp#288]
Hi,

Is it possible to use MSCCL++'s `smchannel` or `proxy_channel` directly within Triton kernels?  If so, could you provide some guidance or pointers on how to properly integrate these communication channels within Triton code? 

Thanks!!

**Comment by chhwang** [comment]
Hi @rajagond, this is a topic under discussion, but we don't have ideas on the feasibility yet. Please put further discussions on Triton's side if you would like to. Thank you!
