### ISSUE TITLE
[Bug] __assert_fail declaration in mscclpp breaks "assert()" usage in host functions.

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [microsoft/mscclpp#302]
Hi,

There is an `__assert_fail` declaration at
https://github.com/microsoft/mscclpp/blame/a3cd95bd423381d4bc15a782be36da078ab1eecd/include/mscclpp/poll_device.hpp#L17

When using `assert()` in host functions, the above `__device__ only` declaration will break the compilation. Example error:

```
error: calling a __device__ function("__assert_fail") from a __host__ function("main") is not allowed
```

Meanwhile, the `__assert_fail` related declaration in `cuda/targets/x86_64-linux/include/crt/common_functions.h` is dual `__host__ __device__`.

**Comment by chhwang** [comment]
Thanks for reporting. Fixed in #303.
