### ISSUE TITLE
[Bug] Bugs in mp_unit_test. 

### ISSUE THREAD

**Issue by TonyWu199** [microsoft/mscclpp#315]
I run `mpirun -np 2 ./test/mp_unit_tests` in tutorials and meet this IB bug in PingPongIb, could you find what is going on?

```
terminate called after throwing an instance of 'mscclpp::IbError'
  what():  a work item failed: status 12 (Ib failure: Cannot allocate memory)
```

Supplement: The ib related tests in PeerToPeerTest runs ok, but fails in the below case using proxyChannels.

I test in these docker images:
ghcr.io/microsoft/mscclpp/mscclpp:base-cuda12.2
ghcr.io/microsoft/mscclpp/mscclpp:base-cuda12.3

**Comment by chhwang** [comment]
You may try `--ulimit memlock=-1:-1` argument of `docker run`. But this may not fix your issue. ibverbs APIs may return `ENOMEM` due to various reasons depending on your system configuration.

**Comment by TonyWu199** [comment]
> You may try `--ulimit memlock=-1:-1` argument of `docker run`. But this may not fix your issue. ibverbs APIs may return `ENOMEM` due to various reasons depending on your system configuration.

Thanks all the same, and could provide your command to run the docker?

**Comment by chhwang** [comment]
> > You may try `--ulimit memlock=-1:-1` argument of `docker run`. But this may not fix your issue. ibverbs APIs may return `ENOMEM` due to various reasons depending on your system configuration.
> 
> Thanks all the same, and could provide your command to run the docker?

You can find from here: https://github.com/microsoft/mscclpp/blob/main/.azure-pipelines/ut.yml#L24
