### ISSUE TITLE
Is there exist some documentation to explain the difference between allreduce algorithm in mscclpp?

### ISSUE THREAD

**Issue by MARD1NO** [microsoft/mscclpp#350]
I'm not very clear the difference of allreduce1/2/3..., and which algorithm should I use in different device(pcie, nvlink, nvls)

**Comment by Binyang2014** [comment]
The allreduce1/2/3 just for test purpose. And we only tested in nvlink device.  Allreduce 1/2/3 is implemented with different algo/interfaces. Algo1: ring-based reduce, Algo2: packet interface, Algo3: reduce-scatter - allgather reduce.

It's just an example to show how to use mscclpp interfaces to write your own algo should not be used in production.

**Comment by MARD1NO** [comment]
> The allreduce1/2/3 just for test purpose. And we only tested in nvlink device. Allreduce 1/2/3 is implemented with different algo/interfaces. Algo1: ring-based reduce, Algo2: packet interface, Algo3: reduce-scatter - allgather reduce.
> 
> It's just an example to show how to use mscclpp interfaces to write your own algo should not be used in production.

Thanks, what about algo6? It seems is target to NVLS, and can it be used in production?(Because I see the benchmark result  is better than nccl implementation)

**Comment by Binyang2014** [comment]
Oh you mean the python benchmark. Yes algo6 is for nvls. And these algo should be tested. You can check the code here: https://github.com/microsoft/mscclpp/blob/26a87535f96967ecf605dfd42b6ccab376b5b455/python/mscclpp_benchmark/allreduce_bench.py#L170-L184 for how to choose different algo for different message size.
Also we have the nccl interface support: https://github.com/microsoft/mscclpp/blob/main/apps/nccl/README.md

You can try to use these algo in your production. Please note that we've included these algorithms just to demonstrate our ability to outperform NCCL. And the algo is just for signal node and two nodes.
Also, we encourage developing your own algo via mscclpp interface

**Comment by MARD1NO** [comment]
> Oh you mean the python benchmark. Yes algo6 is for nvls. And these algo should be tested. You can check the code here:
> 
> https://github.com/microsoft/mscclpp/blob/26a87535f96967ecf605dfd42b6ccab376b5b455/python/mscclpp_benchmark/allreduce_bench.py#L170-L184
> 
> for how to choose different algo for different message size.
> Also we have the nccl interface support: https://github.com/microsoft/mscclpp/blob/main/apps/nccl/README.md
> You can try to use these algo in your production. Please note that we've included these algorithms just to demonstrate our ability to outperform NCCL. And the algo is just for signal node and two nodes. Also, we encourage developing your own algo via mscclpp interface

Thanks for your explanation :D
