### ISSUE TITLE
[Feature] Can NVIDIA and AMD communicate?

### ISSUE THREAD

**Issue by liuyang6055** [microsoft/mscclpp#361]
Hello，

I have a problem，I have an NVIDIA GPU and an AMD GPU.Can these two GPUs communicate with each other by using MSCCL++?

Or rather, MSCCL++is only applicable for mutual communication on the same platform.

Thanks.

**Comment by chhwang** [comment]
We haven't tried, but it would work if you go through IB or Ethernet connections. IPC connections will likely not going to work.
