### ISSUE TITLE
[Feature] Cross-node communication without InfiniBand

### ISSUE THREAD

**Issue by chenhongyu2048** [microsoft/mscclpp#398]
I wonder if msccclpp supports communication between GPUs on two nodes that don't have IB, e.g. in the case of ethernet-only.

**Comment by chhwang** [comment]
We do support either RoCE and TCP.

**Comment by chenhongyu2048** [comment]
Thanks, but I'm still wondering how I should use TCP/Ethernet, should I set Transport to `Ethernet` to do so? 
And in #408 you answer that SmChannel can only use cudaipc, so if I want to use Ethernet, should I choose ProxyChannel?

**Comment by chhwang** [comment]
Yes, ProxyChannel with Ethernet transport will run over TCP.

**Comment by chenhongyu2048** [comment]
Thanks for your reply!
